### ISSUE TITLE
Prefix is not applied in API response to media. Cloud Storage (S3), Postgres beta 10

### ISSUE THREAD

**Issue by BohdanK-W32** [payloadcms/payload-3.0-demo#100]
Media uploads is working correctly, but if you use prefix it's not applied in the API response to the provided file url.
Version: beta 10, S3 (MinIO)

API response:

![image](https://github.com/payloadcms/payload-3.0-demo/assets/38509807/3eca13b1-64d6-42de-b1bd-67d5cbdf3e43)

Response from the file URL:

![image](https://github.com/payloadcms/payload-3.0-demo/assets/38509807/a9ff4e17-833a-4d09-be8c-32914569cf86)

Response with the correctly applied prefix.
Prefix provided in plugin config: `public/media`.
Prefix applied to file URL: `public%2Fmedia%2F`

![image](https://github.com/payloadcms/payload-3.0-demo/assets/38509807/10c9b736-9778-4e21-985e-0783214b8ed0)

MinIO bucket:

![image](https://github.com/payloadcms/payload-3.0-demo/assets/38509807/6b184263-b3c7-4f70-bc3b-7a7582d6907b)

**Comment by denolfe** [comment]
The `prefix` was never meant to modify the URL of the asset, only adjust where it is stored. If you want to adjust this, you could use the `generateFileURL` function to adjust the URL.

There is likely some documentation that could be added to clarify this.
