### ISSUE TITLE
Admin UI returns 404 if global has required fields

### ISSUE THREAD

**Issue by BohdanK-W32** [payloadcms/payload-3.0-demo#103]
`400 /api/form-state`

P.S.: Tested only with Postgres

**Comment by jacobsfletch** [comment]
Hey @BohdanK-W32 I am unable to reproduce this (I am running Postgres). Required global fields appear to be working as expected:

https://github.com/payloadcms/payload-3.0-demo/assets/15735305/4bd5d975-ecab-4ea9-9061-e8362135ad5c

**Comment by BohdanK-W32** [comment]
Right now on my main laptop it's working fine, on another one it returns 400, maybe it's a rare corner case, idk

However, I'll try reproduce it later and send more info bout it
