### ISSUE TITLE
RowLabel does not work in array field

### ISSUE THREAD

**Issue by oladayo21** [payloadcms/payload-3.0-demo#104]
The array field has an `admin.components.RowLabel` config which is meant to customize the displayed label of each row in the admin UI. This does not work however, only the default shows up. 
example config: 
```
{
        name: 'columns',
          type: 'array',
          fields: [
            {
              name: 'title',
              type: 'text',
            },
          ],
          admin: {
            components: {
              RowLabel: (props) => 'Custom Row Label',
            },
          },
        }
```
Admin UI shows:

<img width="746" alt="Bildschirmfoto 2024-04-14 um 22 56 28" src="https://github.com/payloadcms/payload-3.0-demo/assets/89917778/ebea9e1a-c8c7-4c8c-9c45-a8687807d75a">

I expect `Custom Row Label` to show up instead of `Column 01`

**Comment by jmikrut** [comment]
Hey @oladayo21 — this is because `RowLabel` is now a React component, rather than a function. It needs to be placed in a separate file.

Here is an example:

```ts
'use client'

import type { RowLabelComponent } from 'payload/types'

import { useRowLabel } from '@payloadcms/ui/forms/RowLabel/Context'
import React from 'react'

export const ArrayRowLabel: RowLabelComponent = () => {
  const { data } = useRowLabel<{ title: string }>()
  return (
    <div>{data.title || 'Untitled'}</div>
  )
}
```

That should fix it for you!

**Comment by johnlomat** [comment]
Hello @jmikrut I tried this code you mentioned https://github.com/payloadcms/payload-3.0-demo/issues/104#issuecomment-2056887154 in a newly installed payload-3.0 but I'm getting an empty object.
![Screenshot 2024-07-27 190202](https://github.com/user-attachments/assets/d276c6b0-d4f8-44e9-9edc-4b8f7337e684)
![Screenshot 2024-07-27 190328](https://github.com/user-attachments/assets/8847e90f-fbda-434b-9aaa-e960699778df)

**Comment by EmilyYond** [comment]
Hey @johnlomat, I also had this error after updating, but the following seems to have fixed it:

```
'use client'

import type { RowLabelComponent } from 'payload'
import { useRowLabel } from '@payloadcms/ui'
import React, { useEffect, useState } from 'react'

type RowData = {
    id: string
    title?: string
}

export const ArrayRowLabel: RowLabelComponent = (a) => {
    const { data, rowNumber } = useRowLabel<RowData>()
    let backup = `${a?.label} ${rowNumber}`
    const [label, setLabel] = useState(backup)

    useEffect(() => {
        setLabel(data.title || backup)
    }, [data, rowNumber])

    return (
        <div>
            <span>{label}</span>
        </div>
    )
}
```
