### ISSUE TITLE
An image prepared for upload gets unselected when a user starts entering a title

### ISSUE THREAD

**Issue by grvk** [payloadcms/payload-3.0-demo#107]
# Steps to reproduce

1. Clone payloadcms repo (at the moment, the last commit is `6e7f241ce0c9a1e574359bcd94ab1fe6bce264b8`)
2. Update payloadcms libs in `package.json` to version `beta.10`:
<img width="671" alt="Screenshot 2024-04-14 at 4 29 51 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/4755076/db0d3dae-0e3b-4735-91b6-87afb3546bf8">
[package.json](https://github.com/payloadcms/payload-3.0-demo/files/14972364/package.json)
3. Update `payload-config.ts` file with the one attached to the ticket (to enable image uploading):
_I'm using postgresql in this setup, but it shouldn't matter_
<img width="1470" alt="Screenshot 2024-04-14 at 4 31 48 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/4755076/d888ad00-c08c-4a50-8440-0fdc7542eebb">
<img width="1466" alt="Screenshot 2024-04-14 at 4 32 01 PM" src="https://github.com/payloadcms/payload-3.0-demo/assets/4755076/d3d2
[payload.config.ts.txt](https://github.com/payloadcms/payload-3.0-demo/files/14972363/payload.config.ts.txt)
ed8d-6246-466b-b1c6-4ff34ed47275">
4. `npm install`
5. `npm run dev`
6. Log in with admin's credentials
7. Go to `Media` collections
8. Click on "New" to upload a new media file
9. Select an image
10. Start typing title of the image

# Expected Result
1. Image is select for upload
2. Title is entered

# Actual Result
When the title is entered, the selected image disappears (due to rehydration error?)

# Screen recording
https://github.com/payloadcms/payload-3.0-demo/assets/4755076/e73d08ff-b340-4d86-b7a1-6bde3d2a6843

**Comment by denolfe** [comment]
Should be fixed with https://github.com/payloadcms/payload/pull/5823. Will be released in beta.11.
