### ISSUE TITLE
SEO Plugin installation Error

### ISSUE THREAD

**Issue by AdvithShetty** [payloadcms/payload-3.0-demo#109]
I ran following cmd to install SEO plugin = `npm add @payloadcms/plugin-seo`

and got the following error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: igauge@0.1.0
npm ERR! Found: payload@3.0.0-beta.10
npm ERR! node_modules/payload
npm ERR!   payload@"^3.0.0-beta.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer payload@"^2.7.0" from @payloadcms/plugin-seo@2.3.0
npm ERR! node_modules/@payloadcms/plugin-seo
npm ERR!   @payloadcms/plugin-seo@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\advit\AppData\Local\npm-cache\_logs\2024-04-15T04_38_36_831Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\advit\AppData\Local\npm-cache\_logs\2024-04-15T04_38_36_831Z-debug-0.log
```

**Comment by r1tsuu** [comment]
> I ran following cmd to install SEO plugin = `npm add @payloadcms/plugin-seo`
> 
> and got the following error
> 
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: igauge@0.1.0
> npm ERR! Found: payload@3.0.0-beta.10
> npm ERR! node_modules/payload
> npm ERR!   payload@"^3.0.0-beta.10" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer payload@"^2.7.0" from @payloadcms/plugin-seo@2.3.0
> npm ERR! node_modules/@payloadcms/plugin-seo
> npm ERR!   @payloadcms/plugin-seo@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! C:\Users\advit\AppData\Local\npm-cache\_logs\2024-04-15T04_38_36_831Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in: C:\Users\advit\AppData\Local\npm-cache\_logs\2024-04-15T04_38_36_831Z-debug-0.log
> ```

Hello!
i think you were installing plugin-seo 2.3.0 version, weren't you?
try this `npm i @payloadcms/plugin-seo@3.0.0-beta.10`

**Comment by paulpopus** [comment]
Hey @AdvithShetty yeah the above should fix it for you, I just tested it!

Make sure you keep your packages' versions in sync as well as that will help alleviate some issues.

npm/etc by default install the latest available _stable_ version hence you received the 2.x

Gonna close this for now, but let us know if you encounter any further issues!

**Comment by paulpopus** [comment]
@AdvithShetty Can you make sure you import with named imports instead please?
```
import { seo } from '@payloadcms/plugin-seo'
```

And make sure you're on the latest beta across all of our packages, I think it's beta 22 right now
