### ISSUE TITLE
Vercel blob connection failed

### ISSUE THREAD

**Issue by amitsarkerr** [payloadcms/payload-3.0-demo#116]
Hello,

I wanted to use vercel blob storage, but struggling to install [payload cloud storage plugin](https://github.com/payloadcms/plugin-cloud-storage). Also, I can see, that the cloud storage repository is archived.

Is there any suggestion to use vercel blob as storage in payload 3.0 beta ?

**Comment by abel-sch** [comment]
checkout this repo https://github.com/payloadcms/vercel-deploy-payload-postgres

**Comment by amitsarkerr** [comment]
Thank you for your quick reply.

As I am using 3.0 Beta, I am unable to install https://www.npmjs.com/package/@payloadcms/plugin-cloud-storage

**Comment by denolfe** [comment]
>  I can see, that the cloud storage repository is archived.

The readme clearly states that this has been moved to the linked monorepo.

> checkout this repo https://github.com/payloadcms/vercel-deploy-payload-postgres

@amitsarkerr That plugin is working with 3.0 beta. From the above repo that @abel-sch linked:

https://github.com/payloadcms/vercel-deploy-payload-postgres/blob/main/src/payload.config.ts#L34-L46

> Also, payload generate:types does not work.

All appears to be working on latest beta (beta.11). If not, please open a separate issue.
