### ISSUE TITLE
Can't access req inside BeforeNavLinks / AfterNavLinks / CustomNav / components

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload-3.0-demo#118]
In custom views we have access to `initPageResult` object from props which contains `req`
BeforeNavLinks / AfterNavLinks / CustomNav  are rendered as server components as well as custom views too, but we don't have access to `req`.
We only have access to `config` in `CustomNav`.
It makes sense to allow access to `initPageResult` in **all** custom server components i think.
Upd: Providers as well.

**Comment by jmikrut** [comment]
Interesting - I think we could do this. But, the only thing I'd say is that we probably want to be more explicit regarding the naming of `initPageResult` if it becomes globally "a thing". 

Maybe we identify the properties that are nice to have passed, and only pass _**those**_ properties.

@jacobsfletch what do you think?

**Comment by jacobsfletch** [comment]
@r1tsuu what speficially from the `initPageResult` do you need?

**Comment by r1tsuu** [comment]
> @r1tsuu what specifically from the `req` do you need?

I think `req`? Because it contains url, search params, user, `payload`

**Comment by jacobsfletch** [comment]
Related: https://github.com/payloadcms/payload/pull/6355

**Comment by AlessioGr** [comment]
Closing this, as this should be fixed now. While we have not added `req` (there is no "real" req and it would be inconsistent) we have added all relevant properties separately: https://github.com/payloadcms/payload/pull/6355
