### ISSUE TITLE
Beta v11 - API routes throwing an error when attempting to build application

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload-3.0-demo#129]
Hello,

When attempting to build the application after the release of beta.11 I am facing an issue within the payload API routes that prevents me being able to deploy the application.

The errors are as shown below:

```js
Error occurred prerendering page "/app/my-route". Read more: https://nextjs.org/docs/messages/prerender-error
```

```js
error: invalid input syntax for type uuid: "0"
    at {{ MY DIRECTORY }}/.next/server/chunks/4451.js:156:85858
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async {{{ MY DIRECTORY }}/.next/server/chunks/4451.js:175:27164
    at async i9 ({{ MY DIRECTORY }}/.next/server/chunks/4451.js:213:152)
    at async m ({{ MY DIRECTORY }}/.next/server/chunks/4451.js:224:20522)
    at async {{ MY DIRECTORY }}/.next/server/chunks/4451.js:224:8169
    at async {{ MY DIRECTORY }}/.next/server/chunks/4451.js:224:8107
    at async e._batchLoadFn ({{ MY DIRECTORY }}/.next/server/chunks/4451.js:224:8059)
```

I can confirm that on beta 10 and below this issue is not present in the same codebase.

Please let me know if any further info is required.

**Comment by denolfe** [comment]
Interesting, `uuid` lib slipping into the front-end.

Looks related to this PR pulling in the uuid lib https://github.com/payloadcms/payload/pull/5824

**Comment by denolfe** [comment]
I'm not able to recreate this on latest beta. If you can provide a repo that can recreate the error, I can reopen.
