### ISSUE TITLE
getFile route passes Content-Type header only when file is binary type 

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload-3.0-demo#132]
So this is reopening https://github.com/payloadcms/payload-3.0-demo/issues/88
We thought it was fixed in https://github.com/payloadcms/payload/pull/5799 but
It doesn't work when file format is a text format like `svg`, `js` `.csv` etc  https://www.npmjs.com/package/file-type

> file-type
This package is for detecting binary-based file formats, **not text-based formats like .txt, .csv, .svg, etc.**

And because of this we are still getting instead of SVG preview just the code.. It shouldn't work like that.
![image](https://github.com/payloadcms/payload-3.0-demo/assets/64744993/56ae5b7b-5763-48f4-8610-7cac59234e51)

gonna temporary move back to mime-types package in my own payload/next version so i can use beta, but what solution would be?
@JarrodMFlesch

**Comment by JarrodMFlesch** [comment]
Hey @r1tsuu I have this [PR](https://github.com/payloadcms/payload/pull/5958) open if you want to check it out. I still would like to avoid pulling in mime-types if we can.
