### ISSUE TITLE
Edit link form doesn't work in Lexical editor [Beta 11]

### ISSUE THREAD

**Issue by zelenovsky** [payloadcms/payload-3.0-demo#137]
<img width="1236" alt="Screenshot 2024-04-23 at 12 06 03" src="https://github.com/payloadcms/payload-3.0-demo/assets/29061981/77aea713-651d-4002-b123-ac3cd3d65836">

<img width="1006" alt="Screenshot 2024-04-23 at 12 08 36" src="https://github.com/payloadcms/payload-3.0-demo/assets/29061981/78abc4f1-e4d0-4484-9f63-69113125669e">

It is not possible to edit link in image caption now

**Comment by zelenovsky** [comment]
it seems it is in progress 
https://github.com/payloadcms/payload-3.0-demo/issues/135

**Comment by AlessioGr** [comment]
Fixed the issue in https://github.com/payloadcms/payload/pull/5893 !

Will be available in the upcoming beta.15 (not released yet)
