### ISSUE TITLE
Forgot password page does not submit and shows empty error

### ISSUE THREAD

**Issue by JessChowdhury** [payloadcms/payload-3.0-demo#139]
This was reported on discord [here](https://discord.com/channels/967097582721572934/1215659716538273832/1231378921946349568) and I saw the same behavior when trying to replicate [this issue](https://github.com/payloadcms/payload-3.0-demo/issues/136).

Go to `/admin/forgot` and click submit, form does not submit, you see the empty tooltip and toast error. 
No other errors in the terminal or browser, and no failed network requests. 

Payload version: 3.0.0-beta.11

![Screenshot 2024-04-23 at 1 08 48 PM](https://github.com/payloadcms/payload-3.0-demo/assets/67977755/c9b044d6-aa72-4a66-8468-7d5dfd9ceed1)

**Comment by PatrikKozak** [comment]
@JessChowdhury This should be fixed with this [PR](https://github.com/payloadcms/payload/pull/5871) from last week. Might not be in the latest beta version.

Let's see if this is still happening once a new version is released.

**Comment by JessChowdhury** [comment]
Looks good on the latest beta branch - closing!
