### ISSUE TITLE
/admin/logout-inactivity 500 error

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-demo#141]
`beta.14`

upon visiting the `/admin/logout-inactivity` route, I receive the following error. Deleting `.next` and restarting the server did not solve the issue.

```
 ⨯ TypeError: Cannot read properties of undefined (reading 'toString')
    at Array.map (<anonymous>)
digest: "3689927191"
TypeError: Cannot read properties of undefined (reading 'toString')
    at eC (D:\(redacted)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:391023)
    at ex (D:\(redacted)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:391139)
    at D:\(redacted)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:12179
    at Array.map (<anonymous>)
    at ey.icons (D:\(redacted)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:12172)
    at D:\(redacted)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:12294 {
  digest: '3689927191'
}
```

**Comment by JessChowdhury** [comment]
Hi @HarleySalas I'm struggling to recreate this error, could you provide more detailed steps? Did you make any changes to the repo?

I set the `tokenExpiration` to a short duration and there is something else going wrong there but it was different to this error. And going directly to `/admin/logout-inactivity` worked for me.

**Comment by HarleySalas** [comment]
I didn't make any changes to this route. The only thing I do is generate my own token upon login, which works as follows:

```
export const generatePayloadAuthCookie = async ({
  payload,
  user,
  userCollection,
}: GeneratePayloadAuthCookieArgs) => {
  const fieldsToSign = getFieldsToSign({
    collectionConfig: userCollection,
    email: user.email,
    user: {
      ...user,
      /** @ts-ignore */
      collection: userCollection.slug,
    },
  })

  const now = Math.floor(Date.now() / 1000)

  const tokenExpiration =
    typeof userCollection?.auth?.tokenExpiration === 'number'
      ? userCollection.auth.tokenExpiration
      : 7200

  const expTime = now + tokenExpiration

  const token = await new SignJWT(fieldsToSign)
    .setProtectedHeader({ alg: 'HS256', typ: 'JWT' })
    .setIssuedAt()
    .setExpirationTime(expTime)
    .sign(new TextEncoder().encode(payload.secret))

  const cookie = generatePayloadCookie({
    collectionConfig: userCollection,
    payload,
    token,
  })

  return cookie
}
```

I believe the resulting cookie is exactly the same as the one resulting from payload by default. and is the only thing that could possibly be interfering with it.

I `ctrl+shift+f` searched my entire codebase for the `.toString` method and ensured that nothing in my entire project is attempting to call it something is not a string.

I tried to create a production for you. However, the `auth.tokenExpiration` is the amount of time that goes by before a `/api/user/refresh-token` request is made. I do not believe that shortening that would cause logout for inactivity? Can logout for inactivity even be removed/modified? I don't really see anything here at first glance.

**Comment by JessChowdhury** [comment]
@HarleySalas if you comment out your custom `generatePayloadAuthCookie` and check `/admin/logout-inactivity` do you get the same error?

>  Can logout for inactivity even be removed/modified?

The `tokenExpiration` prop is how we would modify this - once the token expires, the user will be logged out. This appears to be a 3.0 bug, if you test it on v2.0 you can see the expected behavior. Setting it `tokenExpiration: 300` (seconds) for example would log the user out after 5 minutes. I will open another issue for this not working.

**Comment by HarleySalas** [comment]
At least when I manually visit that link, it does not throw the error.

There is a *chance* I could have ran the application with `--turbo` when that issue happened to me. At the time, I wasn't aware of so many issues with turbo at the moment. I will open another issue with a reproduction, if it continues to happen when I can test with the fixed iteration of `tokenExpiration`,
