### ISSUE TITLE
BUG - type generation fails on any files that resolve the tailwind config for use

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload-3.0-demo#147]
Hey,

I've updated my project to beta.15 to fix the uuid strings type generation in the db-postgres package however, when generating types now whenever a file contains the following code

```js
import tailwindConfig, { type Colors } from "tailwind.config";
import resolveConfig from "tailwindcss/resolveConfig";

const tw = resolveConfig(tailwindConfig);
const { theme } = tw as unknown as {
	theme: (typeof tw)["theme"] & { colors: Colors };
};
```

the type generation fails with the following error

```
const tw = resolveConfig(tailwindConfig);
           ^

TypeError: resolveConfig is not a function
    at file:///{{ MY DIRECTORY }}/src/assets/AppIcon.tsx:3:12
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async bin (file://{{ MY DIRECTORY }}/node_modules/.pnpm/payload@3.0.0-beta.15_@swc+core@1.4.12_@swc+helpers@0.5.5__@swc+types@0.1.6_graphql@16.8.1/node_modules/payload/dist/bin/index.js:9:27)

Node.js v21.2.0
 ELIFECYCLE  Command failed with exit code 1.
```

If I remove the code to resolve the config the generation begins to work fine again.

**Comment by AlessioGr** [comment]
Hey @mcornielje090404 the quick fix for you would be to change

`import resolveConfig from "tailwindcss/resolveConfig";`

to

`import resolveConfig from "tailwindcss/resolveConfig.js";`

In the meantime, we're working on a fix which doesn't force you to use js extensions in the specifier

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/6090
