### ISSUE TITLE
(minor issue) Backspacing the API depth field results in unhandled runtime error

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-demo#149]
Any API page's depth property when backspaced, results in this unhandled runtime error.

```index.client.js:193 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')```

![image](https://github.com/payloadcms/payload-3.0-demo/assets/38236585/528f0099-97fc-4f56-831c-aae773558712)

**Comment by JessChowdhury** [comment]
@HarleySalas thanks for catching this! Fixed and will go out in next release.
