### ISSUE TITLE
Collection field removed from PayloadRequest

### ISSUE THREAD

**Issue by revnelson** [payloadcms/payload-3.0-demo#150]
Collection config information seems to have been removed from `PayloadRequest`.

v2.* types show:

```typescript
export declare type PayloadRequest<U = any> = Request & {
    /** Information about the collection that is being accessed
     * - Configuration from payload-config.ts
     * - MongoDB model for this collection
     * - GraphQL type metadata
     */
    collection?: Collection;
    /** context allows you to pass your own data to the request object as context
     * This is useful for, for example, passing data from a beforeChange hook to an afterChange hook.
     * payoadContext can also be fully typed using declare module
     * {@link https://payloadcms.com/docs/hooks/context More info in the Payload Documentation}.
     */
    context: RequestContext;
    ...
}
```

I need this for a hook that revalidates next queries that are tagged with the collection slug. Has this been moved, or will this come back?

**Comment by JarrodMFlesch** [comment]
@revnelson the collection property on the request is not coming back, but we have accounted for that!

To obtain the slug of the collection of the current request, you can get it from `req.routeParams.collection` like so:

```ts
import { CollectionAfterChangeHook } from 'payload/types'

const revalidateQueries: CollectionAfterChangeHook = ({ req }) => {
  if (req.routeParams?.collection) {
    const collectionSlug = req.routeParams?.collection
    const entireCollection = req.payload.config.collections.find((c) => c.slug === collectionSlug)

    // revalidate your queries with the slug
  }
}
```

![CleanShot 2024-04-25 at 4  36 17](https://github.com/payloadcms/payload-3.0-demo/assets/30633324/ded8e1fa-801e-43a2-a5f3-d91d8a722ac9)

If you need to obtain the entire config you can use

**Comment by revnelson** [comment]
Fantastic, thank you so much for the answer and code snippet!
