### ISSUE TITLE
Check into `generateStaticParams` and `getPayloadHMR`

### ISSUE THREAD

**Issue by jmikrut** [payloadcms/payload-3.0-demo#157]
Some strange things might be happening if you use `getPayloadHMR` within `generateStaticParams`. This should be fine to do, but because Next.js runs `generateStaticParams` functions in a separate thread, some aspects of Payload like Drizzle pushing schema changes might be conflicting in each separate thread.

**Comment by denolfe** [comment]
It looks like this was caused by calling `getPayload` instead of `getPayloadHMR`. Will keep an eye on it.
