### ISSUE TITLE
[3.0] Conditional fields within arrays not working as expected

### ISSUE THREAD

**Issue by genox** [payloadcms/payload-3.0-demo#162]
### Describe the Bug

When using fields with a condition property within an array, the condition is evaluated but whether it returns true or false has no effect on the visibility of the field.

### To Reproduce

This is a collection that exposes the behaviour:

```ts
import { CollectionConfig } from 'payload/types';

const Product: CollectionConfig = {
  slug: 'product',
  fields: [
    {
      name: 'variantAttributes',
      type: 'select',
      hasMany: true,
      options: [
        { value: 'size', label: 'Size' },
        { value: 'packagingUnit', label: 'Packaging Unit' },
      ],
    },
    {
      type: 'array',
      name: 'variants',
      fields: [
        {
          name: 'size',
          type: 'select',
          admin: {
            condition: (data) => {
              return data?.variantAttributes?.includes('size');
            },
          },
          options: [
            { value: 'xs', label: 'XS' },
            { value: 's', label: 'S' },
            { value: 'm', label: 'M' },
            { value: 'l', label: 'L' },
            { value: 'xl', label: 'XL' },
            { value: 'xxl', label: 'XXL' },
          ],
        },
        {
          name: 'packagingUnit',
          type: 'select',
          admin: {
            condition: (data) => {
              return data?.variantAttributes.includes('packagingUnit');
            },
          },
          options: [
            { value: 'piece', label: 'Piece' },
            { value: 'box', label: 'Box' },
            { value: 'carton', label: 'Carton' },
            { value: 'pouch', label: 'Pouch' },
          ],
        },
      ],
    },
  ],
};

export default Product;

```

Within the array, variant attributes should only be displayed if selected in variantAttributes. It works for the array itself but not for fields within the array.

### Payload Version

3.0-beta.18

### Adapters and Plugins

Postgres

**Comment by JarrodMFlesch** [comment]
Hey @genox I reduced your original snippet down to just a subsection, the piece in question.

The issues you are seeing are coming from the lines where `data?.variantAttributes.includes` is not properly optionally chained like so `data?.variantAttributes?.includes`. I have opened a PR that ensures the error messages will surface for things like this in the future.

[Related PR](https://github.com/payloadcms/payload/pull/6113)

**Comment by genox** [comment]
@JarrodMFlesch Thanks  for the heads up. I actually varied the optional chains to see if one or the other works for trial and error purposes.

If you pop the collection into payload v3 (beta 18) you will see that if you select any attribute from the variant attribute select the array will show with a first item and log the condition attached to the array element and the elements underneath as well, **but all array fields are shown even though they should be conditional**.

**Comment by JarrodMFlesch** [comment]
@genox I did just that, I copied your collection and modified it. If you use optional chaining it will function as you would expect. This will be more obvious now that we are using the proper error route handler linked in the PR above.

**Comment by genox** [comment]
@JarrodMFlesch Ah I see. Thank you. I will give it a go!
