### ISSUE TITLE
Build Error: Could not load the "sharp" module

### ISSUE THREAD

**Issue by samtietjen** [payloadcms/payload-3.0-demo#163]
Hey Guys,

I started getting this error when visiting localhost:3000/admin

```
Build Error
Failed to compile

Next.js (14.3.0-canary.29)
./node_modules/@payloadcms/ui/dist/assets/favicon.svg
Error: Could not load the "sharp" module using the linuxmusl-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --libc=musl --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install

```

This is a fresh install using `npx create-payload-app@beta`.

Any ideas?

Edit: A couple of additional notes.
- Downgrading didn't help. This is happening on both 3.15 and the latest release.
- It happens on both my M3 Mac and Docker.
- I tried adding the dependencies as the error suggests.
- I tried removing sharp from the package.json (because why not).
- This happened after I tried updating the nested docs plugin. I removed the plugin and tried a fresh install as mentioned. Kind of scratching my head.

**Comment by HarleySalas** [comment]
I had this error on Windows as well. It happened after upgrading to `next` `14.3.0-canary.28`. Reverting back to `14.3.0-canary.7` resolved the issue for me.

**Comment by jmikrut** [comment]
@paulpopus did Next bump their internal Sharp dependency? Do we have 2 sharp versions installed?

**Comment by samtietjen** [comment]
@HarleySalas Tried that, but no luck for me.

**Comment by HarleySalas** [comment]
> @HarleySalas Tried that, but no luck for me.
> 
> 

The only other thing I did was repeat the global installing for 'node-gyp', including the OS-specific steps as well and I can say, I never saw the sharp specific error again. I just had two sharp errors simultaneously and after the 'node-gyp' thing, I never saw the sharp error again.

**Comment by paulpopus** [comment]
We're still investigating this, going to chase it up with Nextjs

**Comment by paulpopus** [comment]
Out of curiosity, which package managers and versions and node versions is everyone running into this issue with? I've been replicating it and I want to make sure we have full coverage

**Comment by samtietjen** [comment]
Thanks, Paul! 
npm 10.2.4
yarn 1.22.22
node 21.4.0

**Comment by paulpopus** [comment]
> Thanks, Paul! npm 10.2.4 yarn 1.22.22 node 21.4.0

I got it reproduced with yarn v1 but not npm 10. I'm gonna be annoying here but I want to confirm

If you delete `.next`, `node_modules` and any lock files, and then do `npm install` are you still seeing this?

**Comment by HarleySalas** [comment]
> Out of curiosity, which package managers and versions and node versions is everyone running into this issue with? I've been replicating it and I want to make sure we have full coverage

`node 20.11.1`
`pnpm 8.15.5`

**Comment by samtietjen** [comment]
@paulpopus To double check, I just did a fresh npx create-payload-app@beta, npm install, npm run dev and got the error.

**Comment by samtietjen** [comment]
@paulpopus Just a semi-obvious heads up, this breaks Vercel builds as well. Overriding the defaults there to use npm instead of yarn works as well.

**Comment by vsonth** [comment]
i resolved this in my local with `yarn add sharp --ignore-engines` after running yarn to install. However this issue continues when using docker. I believe node-alpine as base is not recognized by sharp. 

From Docker run


![Screenshot 2024-05-07 at 7 39 27 PM](https://github.com/payloadcms/payload-3.0-demo/assets/17440423/0db48077-7db9-4edc-a176-30f452292ca9)



yarn - v1.22.18
node - v21.6.1
docker desktop - 4.16.2

**Comment by paulpopus** [comment]
Hey all, unfortunately this issue is coming from upstream via [this change](https://github.com/vercel/next.js/pull/61810) on nextjs. Yarn v1 will no longer work on next 14.3 without the `--ignore-engines` flag

We are looking for how to best streamline this on our end but the options are:
- run install with `yarn install --ignore-engines`
- use the latest version of yarn
- use npm/pnpm

For those following up, if you're getting stuck with the create payload app, note that it can accept flags for which package manager to use, so you can install with npm with `npx create-payload-app@beta --use-npm` or `--use-pnpm`
