### ISSUE TITLE
Reset password link returns 404

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload-3.0-demo#167]
Beta.19

- Ensure user is created
- Log out
- Click Reset Password
- Click link that is sent in the email ie. `http://localhost:3000/admin/reset/some-id`
- A 404 will be returned

**Comment by jmikrut** [comment]
Is this a duplicate?
https://github.com/payloadcms/payload-3.0-demo/issues/136

**Comment by denolfe** [comment]
Still an issue in beta.21
