### ISSUE TITLE
generate:graphqlschema script showing "Unknown script"

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload-3.0-demo#176]
Attempting to run the script `pnpm payload generate:graphqlschema` is giving `Unknown script`. This script existed in 2.0.

Looks like changes to `payload/src/bin/index.ts` may have dropped this from the case statement, or this bin script was migrated to our graphql package and isn't being loaded properly.

**Comment by teamowldev** [comment]
Hey guys, thanks for the report, you think in the next version it can be solved or it might take longer? @denolfe @JarrodMFlesch

**Comment by jmikrut** [comment]
This should be all set now. You'd use it like:

```
pnpm payload-graphql generate:schema
```

Let us know how it works for ya!

**Comment by AhmedCoolProjects** [comment]
Thanks it worked
