### ISSUE TITLE
Having `svgr` in next.config conflicts with payload favicon

### ISSUE THREAD

**Issue by iamlinkus** [payloadcms/payload-3.0-demo#178]
Couldn't figure out for the life of me why after updating the template files which add `generatePageMetadata` functions to payload routes it crashes whenever next tries to build payload admin routes. That's until I removed `svgr` from my next.config.

Discord thread on this issue:
https://discord.com/channels/967097582721572934/1235988835582873692

Steps to reproduce:

Add `svgr` to next.config
```js 
// next.config.mjs

import { withPayload } from "@payloadcms/next/withPayload";
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    });
    return config;
  },
};

export default withPayload(nextConfig);

``` 

When next builds payload routes, throws an error: 
```TypeError: Cannot read properties of undefined (reading 'toString')```

Which is because svgr has a problem with the payload favicon here:
![image](https://github.com/payloadcms/payload-3.0-demo/assets/16874184/373b3270-90a7-421b-92a1-10ecda262a67)

**Comment by HarleySalas** [comment]
Not sure if it'll solve this issue, I don't have the time at the moment to check, but the setup you've got for `@svgr/webpack` is not ideal for nextjs. I had issues with the lexical `LinkFeature`, for example, where the icons in the link toolbar weren't loading in (because svgr was destroying them) and fixing my next config fixed all the issues I was having, though I haven't paid attention to, or tried to do the favicon.

In any case, you can include/exclude folders from `@svgr/webpack`; if you reference the docs, it'll be clear how you can exclude the paths that you want to leave alone.

`next.config.mjs` (inside the `nextConfig` object, where your current `@svgr/webpack` configuration is.)
```
  webpack(config) {
    // Grab the existing rule that handles SVG imports
    const fileLoaderRule = config.module.rules.find((rule) => rule.test?.test?.('.svg'))

    config.module.rules.push(
      // Reapply the existing rule, but only for svg imports ending in ?url
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: /url/, // *.svg?url
      },
      // Convert all other *.svg imports to React components
      {
        test: /\.svg$/i,
        issuer: fileLoaderRule.issuer,
        resourceQuery: { not: [...fileLoaderRule.resourceQuery.not, /url/] }, // exclude if *.svg?url
        use: ['@svgr/webpack'],
      },
    )

    // Modify the file loader rule to ignore *.svg, since we have it handled now.
    fileLoaderRule.exclude = /\.svg$/i

    return config
  },
```

**Comment by iamlinkus** [comment]
Hey @HarleySalas would you care to share your exact svgr portion of the config? The code you've provided (from svgr docs) results in the same exact error.

**Comment by iamlinkus** [comment]
I think this issue is related:

https://github.com/vercel/next.js/issues/48177#issuecomment-1506251112

**Comment by HarleySalas** [comment]
> Hey @HarleySalas would you care to share your exact svgr portion of the config? The code you've provided (from svgr docs) results in the same exact error, and when explicitly excluding `/node_modules` (where the payload favicon is) it then throws an error:
> 
> ```
>  ⨯ ...........node_modules/@payloadcms/ui/dist/assets/favicon.svg
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
> ```

You could try this, but I haven't tested that it works (to exclude `favicon.svg` from @svgr/webpack)
```
module.exports = {
  webpack(config) {
    // Grab the existing rule that handles SVG imports
    const fileLoaderRule = config.module.rules.find((rule) =>
      rule.test?.test?.('.svg'),
    );

    config.module.rules.push(
      // Reapply the existing rule, but only for svg imports ending in ?url or named 'favicon.svg'
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: /url/, // *.svg?url
      },
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: /favicon/, // favicon.svg
      },
      // Convert all other *.svg imports to React components
      {
        test: /\.svg$/i,
        issuer: fileLoaderRule.issuer,
        resourceQuery: { not: [...fileLoaderRule.resourceQuery.not, /url/, /favicon/] }, // exclude if *.svg?url or favicon.svg
        use: ['@svgr/webpack'],
      },
    );

    // Modify the file loader rule to ignore *.svg, since we have it handled now.
    fileLoaderRule.exclude = /\.svg$/i;

    return config;
  },

  // ...other config
};
```

I do not have the issue, because I provide `.ico` files for my favicons, rather than having next automatically convert them.

**Comment by iamlinkus** [comment]
@HarleySalas the reason I created this issue in the payload repo was because payload uses favicon.svg, not my project. Now that @jmikrut took notice of this and assigned this issue to @jacobsfletch , really hoping this gets resolved. Until then I've commented out the `generatePageMetadata` functions in payload template files.

**Comment by HarleySalas** [comment]
> @HarleySalas the reason I created this issue in the payload repo was because payload uses favicon.svg, not my project. Now that @jmikrut took notice of this and assigned this issue to @jacobsfletch , really hoping this gets resolved. Until then I've commented out the `generatePageMetadata` functions in payload template files.

ahh, gotcha. well, my edit about the filename should clarify everything about how they need to fix it

**Comment by jacobsfletch** [comment]
Hey @iamlinkus and @HarleySalas, just merged a fix for this in https://github.com/payloadcms/payload/pull/6347. There are now PNG exports for the favicon in both light and dark modes. So if you need to use SVGO in your application, it will not try and compile the favicon.svg anymore, because it is no longer being imported by default. This was actually a good opportunity to replace with `admin.favicon` with `admin.icons` straight from Next.js. This is slated to go out in the next beta release, thanks for the report 👍

**Comment by hcsvnt** [comment]
@jacobsfletch , still can't seem to get this to work. What am I missing here?

```
"next": "14.3.0-canary.28",
 "payload": "^3.0.0-beta.32",

``` 

```
 webpack(config) {
        const fileLoaderRule = config.module.rules.find(rule => rule.test?.test?.('.svg'));

        config.module.rules.push(
            // Reapply the existing rule, but only for svg imports ending in ?url
            {
                ...fileLoaderRule,
                test: /\.svg$/i,
                resourceQuery: /url/ // *.svg?url
            },
            // Convert all other *.svg imports to React components
            {
                test: /\.svg$/i,
                issuer: fileLoaderRule.issuer,
                resourceQuery: { not: [...fileLoaderRule.resourceQuery.not, /url/] }, // exclude if *.svg?url
                use: ['@svgr/webpack']
            }
        );

        // Modify the file loader rule to ignore *.svg, since we have it handled now.
        fileLoaderRule.exclude = /\.svg$/i;
        return config;
    },
```
    
    ```
meta: {
            icons: {
                icon: '/assets/images/logo.png'
            }
        },
        components: {
            graphics: {
                Logo: CMSLogo,
                Icon: CMSLogo
            }
        }
```

**Comment by jacobsfletch** [comment]
@hcsvnt is this only when you add the `@svgr/webpack`? That error seems unrelated. I don't believe your icon is properly formatted either, types are probably not tight enough there. https://github.com/payloadcms/payload/pull/6227/files should help with this. Here's an example of a properly formatted `icons` config:

`payload.config.ts`:

```ts
import { default as customFaviconDark } from './custom-favicon-dark.png'
import { default as customFaviconLight } from './custom-favicon-light.png'

{
  // ...
  admin: {
    meta: {
      icons: [
        {
          type: 'image/png',
          rel: 'icon',
          url: customFaviconDark.src,
        },
        {
          type: 'image/png',
          media: '(prefers-color-scheme: dark)',
          rel: 'icon',
          url: customFaviconLight.src,
        },
      ],
    },
  }
}
```

Source: https://github.com/payloadcms/payload/blob/beta/test/admin/config.ts#L86
