### ISSUE TITLE
`en` must always be included in the `supportedLanguages` config

### ISSUE THREAD

**Issue by linobino1** [payloadcms/payload-3.0-demo#182]
I would expect to be able to setup the app without support for english i18n.

Repro:

remove `en` from `i18n.supportedLanguages` in `payload.config.ts` and the app will throw an error like:

```
GET /admin/login 500 in 4700ms
 ⨯ node_modules/.pnpm/@payloadcms+translations@3.0.0-beta.22/node_modules/@payloadcms/translations/dist/utilities/getTranslationsByContext.js (56:1) @ getTranslationsByContext
 ⨯ TypeError: Cannot read properties of undefined (reading 'translations')
    at Object.onInit (./payload.config.ts:88:45)
digest: "2979162757"
  54 |     }
  55 |     else {
> 56 |         return selectedLanguage.translations;
     | ^
  57 |     }
  58 | };
  59 | //# sourceMappingURL=getTranslationsByContext.js.map
 ⨯ node_modules/.pnpm/@payloadcms+translations@3.0.0-beta.22/node_modules/@payloadcms/translations/dist/utilities/getTranslationsByContext.js (56:1) @ getTranslationsByContext
 ⨯ TypeError: Cannot read properties of undefined (reading 'translations')
    at Object.onInit (./payload.config.ts:88:45)
digest: "2979162757"
  54 |     }
  55 |     else {
> 56 |         return selectedLanguage.translations;
     | ^
  57 |     }
  58 | };
  59 | //# sourceMappingURL=getTranslationsByContext.js.map
 ⨯ node_modules/.pnpm/@payloadcms+translations@3.0.0-beta.22/node_modules/@payloadcms/translations/dist/utilities/getTranslationsByContext.js (56:1) @ getTranslationsByContext
 ⨯ TypeError: Cannot read properties of undefined (reading 'translations')
    at Object.onInit (./payload.config.ts:88:45)
digest: "2979162757"
  54 |     }
  55 |     else {
> 56 |         return selectedLanguage.translations;
     | ^
  57 |     }
  58 | };
  59 | //# sourceMappingURL=getTranslationsByContext.js.map
 ⨯ node_modules/.pnpm/@payloadcms+translations@3.0.0-beta.22/node_modules/@payloadcms/translations/dist/utilities/getTranslationsByContext.js (56:1) @ getTranslationsByContext
 ⨯ TypeError: Cannot read properties of undefined (reading 'translations')
    at Object.onInit (./payload.config.ts:88:45)
digest: "2979162757"
  54 |     }
  55 |     else {
> 56 |         return selectedLanguage.translations;
     | ^
  57 |     }
  58 | };
  59 | //# sourceMappingURL=getTranslationsByContext.js.map
```

**Comment by alsherif-khalaf** [comment]
How could supported language be added ?

![image](https://github.com/payloadcms/payload-3.0-demo/assets/73169053/03002306-701d-47da-907b-1512acc414dc)

**Comment by alsherif-khalaf** [comment]
> How could supported language be added ?
> 
> ![image](https://private-user-images.githubusercontent.com/73169053/332528018-03002306-701d-47da-907b-1512acc414dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTQxNzYsIm5iZiI6MTcxNjMxMzg3NiwicGF0aCI6Ii83MzE2OTA1My8zMzI1MjgwMTgtMDMwMDIzMDYtNzAxZC00N2RhLTkwN2ItMTUxMmFjYzQxNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE3NTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMjFlYmMxMDYzOGUxZGQ2ZGJjZGMzYjcwMGIwODUxMWU3MTg5NjEwMDA4ZjJjMmQyMjRlMWU0YTk3Njc1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lVVDUugCaAIc9NrJFCnPFM27TsmJTERKjPJKA1lNLIU)

![image](https://github.com/payloadcms/payload-3.0-demo/assets/73169053/888b8cb7-df39-4c1c-b4ce-4c9d2be30739)
