### ISSUE TITLE
Custom GraphQL resolvers lead to a client-component error

### ISSUE THREAD

**Issue by geisterfurz007** [payloadcms/payload-3.0-demo#187]
Including a section like
```ts
  graphQL: {
    queries: (graphQL, context) => ({
      foo: {
        type: graphQL.GraphQLString,
        args: {},
        resolve: async () => 'foo',
      }
    })
  }
```
in the config causes this error to show up:

```
 ⨯ Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  {disablePlaygroundInProduction: true, maxComplexity: ..., queries: function queries}
                                                                     ^^^^^^^^^^^^^^^^
    at stringify (<anonymous>)
digest: "974511973"
```

which is weird because GraphQL resolvers shouldn't be around on the client-side of things by my understanding.

---

Full repro with [a repository](https://github.com/geisterfurz007/payload-3.0-graphql-repro):

1. Clone the repository `git clone git@github.com:geisterfurz007/payload-3.0-graphql-repro.git`
2. Install dependencies `yarn`
3. Start the database `./start-database.sh`
4. Start the dev server `yarn dev`
5. Open http://localhost:3000/admin
6. *poof*

---

The issue is reproducible with and without the `--turbo` pack as well as on latest stable and latest canary of Next.

**Comment by jacobsfletch** [comment]
Thanks for the report @geisterfurz007 I was able to reproduce this using your repo 👍 very strange though considering we are explicitly deleting the `graphQL` key off from the client config here: https://github.com/payloadcms/payload/blob/beta/packages/payload/src/config/client.ts#L74

**Comment by jacobsfletch** [comment]
@geisterfurz007 I'm now seeing this was fix in https://github.com/payloadcms/payload/pull/6196 but has yet to be released. It will go out in the next beta version.

**Comment by geisterfurz007** [comment]
Yup! Can confirm this is fixed with beta.25, thanks!
