### ISSUE TITLE
Slate editor crashes when user selects list (ul / ol) options

### ISSUE THREAD

**Issue by grvk** [payloadcms/payload-3.0-demo#188]
# Steps to Reproduce

1. Clone [payload-3.0-demo-bugs](https://github.com/grvk/payload-3.0-demo-bugs) 
_Note: it's based of the latest demo code + upgraded to `beta.25`_
2. `npm install` (node version `v18.20.2`)
3. `./start-database.sh`
4. `npm run dev`
5. Log in
6. Click on "Pages"
7. In rich editor select list options

# Expected Result
`<li>` are added to the editor with either visible bullets or numbers (`1.` etc)

# Actual Result
In this particular codebase the whole UI becomes unusable (crashes?)
Before (older versions of the editor) I saw an issue when bullets and numbers wouldn't display

# Recording

https://github.com/payloadcms/payload-3.0-demo/assets/4755076/b452b82d-519b-40e6-b3f5-e75db01ac149

**Comment by PatrikKozak** [comment]
Hey @grvk - good find! 

This issue has been fixed with this [PR](https://github.com/payloadcms/payload/pull/6291).

Just merged it, we'll get a new release out asap and this will be resolved, thank you!
