### ISSUE TITLE
I use image formatOptions in v3 but it doesn't work 

### ISSUE THREAD

**Issue by lctone** [payloadcms/payload-3.0-demo#194]
I use image formatOptions in v3 but it doesn't work 

```
 upload: {
    staticDir: 'media',
    mimeTypes: ['image/*'],
    formatOptions: {
      format: 'webp',
      options: {
        quality: 80,
      },
    },
  },
```

Payload 3 beta 24

Thank you

**Comment by denolfe** [comment]
@lctone Can you confirm you are providing `sharp` to your config?

**Comment by lctone** [comment]
Thanks it was my mistake, forgot to configure sharp in version 3
