### ISSUE TITLE
Postgres transaction error [Beta 26]

### ISSUE THREAD

**Issue by zelenovsky** [payloadcms/payload-3.0-demo#196]
Some times postgres connection gets dropped with this error without any trace:
`Error: cannot begin transaction: Cannot read properties of undefined (reading 'transaction')`

It didn't happen on beta 22

Do you have any ideas?

**Comment by jmikrut** [comment]
Hey @zelenovsky we have been seeing sporadic reports of this going back all the way to Alpha. We have a theory about why this happens, but we can’t reproduce it ourselves consistently. Any chance you can help us reproduce? Did you have a certain set of steps that makes this happen consistently with your project?

**Comment by zelenovsky** [comment]
@jmikrut I noticed that it started to happen when I add a custom Switcher component here:

```js
admin: {
    user: Users.slug,
    components: {
      actions: [Switcher]
    }
  },
```
and inside this component I use getPayload fn. When I remove this component I don't receive this error

**Comment by jmikrut** [comment]
hey @zelenovsky I think we have gotten to the bottom of this one. A new beta will come out today, and after which, will you let us know if you see this happen again?
