### ISSUE TITLE
Adding `defaultSort` to collection config breaks relationship field search.

### ISSUE THREAD

**Issue by iamlinkus** [payloadcms/payload-3.0-demo#197]
How to reproduce:

1. Pull this repo.
2. Modify the `pages` collection like so:

```js 
    {
      slug: 'pages',
      admin: {
        useAsTitle: 'title',
      },
      defaultSort: 'createdAt',
      fields: [
        {
          name: 'relationship',
          type: 'relationship',
          relationTo: 'pages',
        },
        {
          name: 'title',
          type: 'text',
        },
      ],
    },
```
3. `npm run dev`, login to the admin, create a few pages.
4. Open one page, click on the relationship field and start typing.

The field errors out. And the errors are different. Sometimes it's something like

```cmd
ERROR: TypeError: Cannot destructure property 'operator' of '(0 , _sanitizeQueryValue_js__WEBPACK_IMPORTED_MODULE_3__.sanitizeQueryValue)(...)' as it is undefined.
    at buildSearchParam (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+db-mongodb@3.0.0-beta.22_payload@3.0.0-beta.22/node_modules/@payloadcms/db-mongodb/dist/queries/buildSearchParams.js:58:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If I add a `date` field and it's set in all pages and I set it to be the `defaultSort: '-date'`, it's:
```cmd
ERROR: QueryError: The following path cannot be queried: -date
```

**Comment by andershermansen** [comment]
Note that this is an existing bug in v2. Ref https://github.com/payloadcms/payload/issues/4815
I suggested a fix for v2 in https://github.com/payloadcms/payload/pull/5964 but have not yet heard from the maintainers.

**Comment by andershermansen** [comment]
Fix for v2 is merged.
Fix for v3 is ready for review https://github.com/payloadcms/payload/pull/6440

**Comment by denolfe** [comment]
Merged for v2 and v3.
