### ISSUE TITLE
@payloadcms/plugin-form-builder has import errros in 3.x beta 28

### ISSUE THREAD

**Issue by ahmetskilinc** [payloadcms/payload-3.0-demo#198]
### Describe the Bug

When importing `import { formBuilderPlugin } from "@payloadcms/plugin-form-builder"` there is an error that it is not declared (screenshots below).

<img width="1022" alt="Screenshot 2024-05-09 at 17 02 26" src="https://github.com/payloadcms/payload/assets/37756565/087edaad-6943-4161-a22a-5540fc212ced">

<img width="487" alt="Screenshot 2024-05-09 at 17 04 52" src="https://github.com/payloadcms/payload/assets/37756565/49384e09-a746-4769-9ba9-8d4ff4c689ad">

<img width="520" alt="Screenshot 2024-05-09 at 17 07 34" src="https://github.com/payloadcms/payload/assets/37756565/6a0ce5ad-b88b-4f5d-a043-25e8ed5c66a5">

### To Reproduce

`import { formBuilderPlugin } from "@payloadcms/plugin-form-builder"`

### Payload Version

3.0.0-beta.28

### Adapters and Plugins

plugin-form-builder

**Comment by paulpopus** [comment]
This will be fixed in the next beta release
