### ISSUE TITLE
Unable to use the Local API with server components.

### ISSUE THREAD

**Issue by lynndylanhurley** [payloadcms/payload-3.0-demo#199]
Should it be possible to do something like this from a server component?

```tsx
import React from 'react';
import configPromise from '@payload-config';
import { getPayload, type Payload } from 'payload';
import Header from './Header';
import Footer from './Footer';

export default async function Page({ children }: { children: React.ReactNode }) {
  const payload = await getPayload({ config: configPromise });
  const navData = await payload.findGlobal({
    slug: 'nav'
  });

  return (
    <>
      <Header {...navData} />
      {children}
      <Footer />
    </>
  );
}
```

When I try to do this, I get errors about the `payload.config.ts` file trying to import native node packages (i.e. `fs`, `path`, etc):

```
Module not found: Can't resolve 'path'
  13 | import { vercelBlobStorage } from '@payloadcms/storage-vercel-blob';
  14 | import dotenv from 'dotenv';
> 15 | import path from 'path';
     | ^
  16 | import { buildConfig } from 'payload/config';
  17 | import { fileURLToPath } from 'url';
```

I've tried lots of things, including wrapping the fetch functionality in a server-only action, but I get the same errors regardless.

Is what I'm trying to do even a design goal of this lib? Or should we strictly be fetching data via API calls?

**Comment by jmikrut** [comment]
Hey @lynndylanhurley — this is 100% possible and definitely a goal of Payload to support.

I have no idea why you are seeing this error though. We will probably need a minimally reproducible error to spot what you're doing incorrectly here. It seems to me like the component in question is actually being treated as a client component, but from your snippet you don't have `use client` at the top, so I'm not sure why that would be.

Can you get us access to a minimally reproducible environment that we can help diagnose with? This is confirmed to work right now so it is 100% something with your setup. 

Let me know!

**Comment by jmikrut** [comment]
Hey @lynndylanhurley — I believe we've fixed this issue with some improvements to our config loader.

Will you try again and open a new issue if the problem persists?

**Comment by lynndylanhurley** [comment]
oh that's excellent. I'll test this today and let you know how it goes @jmikrut
