### ISSUE TITLE
Breadcrumbs are incorrect after uploading or choosing from existing upload items.

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-demo#202]
Inside a collection that uses an `upload` field, clicking `Upload new Media` or `Choose from existing`, but *not* editing an already selected `Upload` will cause the page's breadcrumbs to change to your `upload` collection.

IE;
I'm editing a collection called "video".
I choose an existing upload for it's cover image, by selecting an existing item, or uploading a new one.
Breadcrumbs are now incorrect for the page.

`payload@beta.29`

**Comment by PatrikKozak** [comment]
Hey @HarleySalas - this is fixed with the above PR, good find! Thank you!
