### ISSUE TITLE
useTranslation and useConfig aren't functions?

### ISSUE THREAD

**Issue by ahmetskilinc** [payloadcms/payload-3.0-demo#203]
I'm trying to update a custom component which works with 2.x to a 3.x component and I'm running into this error for `useTranslation`:
```
> 56 |  const { i18n, t } = useTranslation();

⨯ src/payload/_views/MediaList.tsx (56:36) @ useTranslation
⨯ TypeError: (0 , _payloadcms_ui_providers_Translation__WEBPACK_IMPORTED_MODULE_9__.useTranslation) is not a function
    at MediaList (./src/payload/_views/MediaList.tsx:43:109)
    at stringify (<anonymous>)
```
Same issue with `useConfig`:
```
> 61 | 	} = useConfig();

⨯ src/payload/_views/MediaList.tsx (61:15) @ useConfig
⨯ TypeError: (0 , _payloadcms_ui_providers_Config__WEBPACK_IMPORTED_MODULE_8__.useConfig) is not a function
    at MediaList (./src/payload/_views/MediaList.tsx:42:144)
    at stringify (<anonymous>)
```
Apparently useTranslation and useConfig aren't functions.

I've put the files I'm trying to use in a [gist](https://gist.github.com/ahmetskilinc/be0cf5b29b266c01c452c6ea486a1f8b)

**Comment by paulpopus** [comment]
Hey @ahmetskilinc I believe this is because you're missing the `'use client'` directive at the very top of your file. With 3.0 we're using RSCs which means that in order to be able to use any React hooks (inluding Payload provided ones) you need to opt your component into client side hydration. Let me know if that fixes your issue

**Comment by ahmetskilinc** [comment]
Hey @paulpopus thanks for your response. I'm already using `'use client'` but I now have a weird issue where the file in the gist I posted isn't showing up, but when I test with an empty view that does show up.

**Comment by jmikrut** [comment]
Hey @ahmetskilinc — what Payload version are you on? Do you have matching versions for `next`?

@AlessioGr just fixed an issue with how we detect server vs. client components and I am wondering if that is related. Let me know if you are on latest beta or not.

**Comment by ahmetskilinc** [comment]
Hey @jmikrut I'm using
Payload 	3.0.0-beta.30
Next 		14.3.0-canary.40
Are they the matching versions?

**Comment by paulpopus** [comment]
Out of curiosity @ahmetskilinc can you try using a Server component included into payload and then inside your server component import your client component with all the hooks. This pattern _should_ work

**Comment by ahmetskilinc** [comment]
Thanks @paulpopus, thats worked for loading the component in and I don't have anymore of the original errors in this issue.

I just don't have anything showing up because of issue #204.

**Comment by paulpopus** [comment]
Nice I'll close this then, we'll see about improving DX in this area to be more clear
