### ISSUE TITLE
Payload Stability

### ISSUE THREAD

**Issue by nebrelbug** [payloadcms/payload-3.0-demo#227]
It's time for me to do my yearly personal website rebuild! 

I'd love to use Payload. Do you think the prjoect is stable enough that I could build my website using this template, without having to make major changes as Payload approaches a stable release?

**Comment by jmikrut** [comment]
Hey @nebrelbug — we don't foresee many things changing from how Payload works between now and the full stable 3.0 release, so I'd say go for it! 

The only thing that I can see changing is that we are going to be improving the Postgres database adapter a bit, and you'll need to run a database migration before 3.0 stable launches.

But we'll be giving that migration to you, so it will be very easy for you to do.

Go for it! Let us know how it goes!

**Comment by nebrelbug** [comment]
@jmikrut awesome! Looking forward to it!
