### ISSUE TITLE
Client components dont work inside of Payload `CollectionConfig.admin.components.views.List.Component`

### ISSUE THREAD

**Issue by ahmetskilinc** [payloadcms/payload-3.0-demo#228]
When using the `use client` directive inside a component in Payload beta.34 it causes the following error.

<img width="982" alt="Screenshot 2024-05-18 at 01 27 18" src="https://github.com/payloadcms/payload-3.0-demo/assets/37756565/45c98e28-c5ae-42de-baf3-de307a2426b4">

MediaGrid.client.tsx:
```tsx
"use client";

const MediaGridClient = (props: any) => {
	return (
		<h1>Media</h1>
	);
};
```

MediaGrid.tsx: 
```tsx
const MediaGrid = (props: any) => {
	return (
		<MediaGridClient {...props} />
	);
};
```

Media.ts:
```typescript
const Media: CollectionConfig = {
	slug: "media",
	admin: {
		components: {
			views: {
				List: {
					Component: MediaGrid,
				},
			},
		},
	},
};
```

Why I need it to be a client component is to use the hooks provided by Payload:
```typescript
const {
	breakpoints: { s: smallBreak },
} = useWindowInfo();

const { i18n, t } = useTranslation();

const {
	admin: { dateFormat },
	routes: { admin: adminRoute },
} = useConfig();
```

**Comment by r1tsuu** [comment]
`MediaClient` is a server component and Payload passes `payload` and `i18n` props to them.
They you're passing all those props into a client component `MediaGridClient`.

What you want instead:

create this helper:
```ts
export const getClientProps = (props: Record<string, unknown>) => {
  const copy = { ...props };

  delete copy['payload'];
  delete copy['i18n'];

  return copy;
};
```

then:
```ts
const MediaGrid = (props: any) => {
	return (
		<MediaGridClient {...getClientProps(props)} />
	);
};
```

i believe it should solve your case

**Comment by r1tsuu** [comment]
There's also a helper `withMergedProps` from `payloadcms/ui` but it's a bit verbose to use.
```ts
import { withMergedProps } from '@payloadcms/ui/elements/withMergedProps'

const SanitizedMediaGridClient = withMergedProps({
  Component: MediaGridClient,
  sanitizeServerOnlyProps: true,
})

const MediaGrid = (props: any) => {
	return (
		<SanitizedMediaGridClient {...props} />
	);
};
```

**Comment by ahmetskilinc** [comment]
@r1tsuu just tried your first solution and its still causing the issue
```tsx
import React from "react";
import MediaGridClient from "./TestMediaGrid.client";

export const getClientProps = (props: Record<string, unknown>) => {
	const copy = { ...props };

	delete copy["payload"];
	delete copy["i18n"];

	return copy;
};

const MediaGrid = (props: any) => {
	const clientProps = getClientProps(props);

	return <MediaGridClient {...clientProps} />;
};

export default MediaGrid;
```

And for the second solution its asking for `toMergeIntoProps` to be populated.
<img width="1155" alt="Screenshot 2024-05-18 at 15 07 30" src="https://github.com/payloadcms/payload-3.0-demo/assets/37756565/312f34d6-e40a-427d-81ff-38bcb6c429fa">

**Comment by r1tsuu** [comment]
> @r1tsuu just tried your first solution and its still causing the issue
> 
> ```tsx
> import React from "react";
> import MediaGridClient from "./TestMediaGrid.client";
> 
> export const getClientProps = (props: Record<string, unknown>) => {
> 	const copy = { ...props };
> 
> 	delete copy["payload"];
> 	delete copy["i18n"];
> 
> 	return copy;
> };
> 
> const MediaGrid = (props: any) => {
> 	const clientProps = getClientProps(props);
> 
> 	return <MediaGridClient {...clientProps} />;
> };
> 
> export default MediaGrid;
> ```
> 
> And for the second solution its asking for `toMergeIntoProps` to be populated. <img alt="Screenshot 2024-05-18 at 15 07 30" width="1155" src="https://private-user-images.githubusercontent.com/37756565/331807025-312f34d6-e40a-427d-81ff-38bcb6c429fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDIwODcsIm5iZiI6MTcxNjA0MTc4NywicGF0aCI6Ii8zNzc1NjU2NS8zMzE4MDcwMjUtMzEyZjM0ZDYtZTQwYS00MjdkLTgxZmYtMzhiY2I2YzQyOWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE0MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjgxNjI5ZWE4MzkwYjM0MzFmMDkxNWFhODViNWUyYjg4MzBkZDYxNWEyMjQ3MDMwMmRmNjBjZjJhYzVmOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwIkXHFasyYTHYnN3nSaU_LVnGf8bJVwnORq6EMbDFU">

try `toMergeIntoProps: {}`

**Comment by ahmetskilinc** [comment]
@r1tsuu hmm still the same.
```tsx
const SanitizedMediaGridClient = withMergedProps({
	Component: MediaGridClient,
	sanitizeServerOnlyProps: true,
	toMergeIntoProps: {},
});
```

**Comment by ahmetskilinc** [comment]
@r1tsuu So I managed to get it to work by also deleting `collectionConfig` from the props.

```javascript
delete copy["payload"];
delete copy["i18n"];
delete copy["collectionConfig"];
```

**Comment by r1tsuu** [comment]
> @r1tsuu So I managed to get it to work by also deleting `collectionConfig` from the props.
> 
> ```js
> delete copy["payload"];
> delete copy["i18n"];
> delete copy["collectionConfig"];
> ```

seems like this prop is specific to ListView component
but i think `withMergedProps` ideally should handle this

**Comment by ahmetskilinc** [comment]
Can be closed. Found that using hooks is the way to go with 3.x.
