### ISSUE TITLE
Generating types does not account for UUID id's with Postgres Adaptor

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload-3.0-demo#49]
When generating types in payload with the Postgres Adapter and an idType of 'uuid' the Id's are still typed as numbers even though the database is using uuid's as expected.

The db adapter setup is as below:

```ts
db: postgresAdapter({
  idType: "uuid",
  pool: {
    connectionString: process.env.POSTGRES_URI || "",
  },
})
```

And the types are all typed with numbers:

```ts
export interface Organisation {
  id: number;
  createdBy?: (number | null) | User;
  createdAt?: string | null;
  modifiedBy?: (number | null) | User;
  modifiedAt?: string | null;
  name: string;
}
```

**Comment by denolfe** [comment]
@mcornielje090404 Thanks for the report. This will be fixed in the next release.
