### ISSUE TITLE
Aliasing server-only modules

### ISSUE THREAD

**Issue by joshuatazrein** [payloadcms/payload-3.0-demo#78]
Hi,

How do I alias server-only modules with the new Beta platform? Typically it was done with the `admin.webpack` custom config, but that property is gone now—what's the strategy now?

[Payload docs](https://payloadcms.com/docs/admin/excluding-server-code#aliasing-server-only-modules)

**Comment by KeziahMoselle** [comment]
Did you try extending the Webpack configuration in the `next.config.js` file?

https://nextjs.org/docs/pages/api-reference/next-config-js/webpack

**Comment by jacobsfletch** [comment]
@joshuatazrein Webpack has been completely removed from 3.0 and we now we rely solely on Next.js for bundling. This means that the `admin.bundler` property of 2.0 no longer exists (same with `admin.webpack` and `admin.vite`. Server-only code is automatically kept out of the client-side bundle thanks to React Server Components and the `use client` directive. Write whatever server-only code you wish, and the compiler intelligently knows which to ship to the client, and which to not. As @KeziahMoselle mentioned, though, you _do_ have direct access to your Next config, which contains settings to further control _their_ compiler. I still don't think there's going to be much need for aliasing going forward, though.

**Comment by joshuatazrein** [comment]
https://github.com/payloadcms/payload-3.0-demo/issues/93
