### ISSUE TITLE
Generated ids for an array items in globals can be the same

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload-3.0-demo#80]
Generated ids for an array items in globals can be the same. It could be for blocks as well i think.
To reproduce this just add to the globals config:
` {
      slug: 'test',
      fields: [
        {
          name: 'arr',
          type: 'array',
          fields: [],
        },
      ],
    },
`
<img width="663" alt="image" src="https://github.com/payloadcms/payload-3.0-demo/assets/64744993/98f43220-becb-485d-aecc-b2f80afdd96d">
<img width="1420" alt="image" src="https://github.com/payloadcms/payload-3.0-demo/assets/64744993/a38e0b1d-9dd5-4705-a36e-dce94dc706f1">

Update: it only happens if you'll save the global and then add new items, their id will be the same as the global's id.

**Comment by r1tsuu** [comment]
@jmikrut i see you assigned yourself, can i PR still?

**Comment by PatrikKozak** [comment]
Closing this issue - fixed with this [PR](https://github.com/payloadcms/payload/pull/5795)
