### ISSUE TITLE
PostgreSQL: Pagination missing in list view

### ISSUE THREAD

**Issue by tobiasiv** [payloadcms/payload-3.0-demo#85]
The pagination is missing in the list view when using PostgreSQL. 
It works fine when using MongoDB.

I'm using payload 3.0.0-beta.2 and have cloned this repository.

Screenshot:    

![pagination-missing](https://github.com/payloadcms/payload-3.0-demo/assets/79996819/03b0bd23-fa8b-474d-8c05-e0b954436d0b)

**Comment by paulpopus** [comment]
Should be fixed in latest beta
