### ISSUE TITLE
Merged page including user information and page collection result

### ISSUE THREAD

**Issue by remy90** [payloadcms/payload-3.0-demo#87]
With 3.0.0-beta.0, when I create my first user, I'm presented with this screen:
 ![Screenshot 2024-04-11 at 17 22 13](https://github.com/payloadcms/payload-3.0-demo/assets/47695385/3784c1b0-2460-45b7-a912-fe45d82462d9)
You'll notice from the 3.0 demo that the 'pages' collection has merged with user.

If I fill in the user fields and navigate to pages, I'll see the user information and the actions such as "Change Password" and "Force Unlock", as well as the page fields.

If I navigate to `/admin/account`, I see account settings and page related content:
![Screenshot 2024-04-11 at 17 34 39](https://github.com/payloadcms/payload-3.0-demo/assets/47695385/71f17311-6841-44a4-ae21-be1cdd51cabb)

I initially thought this was related to useApiKey. As soon as I set this to true on any collection, I was unable to login, however, with a clean slate, I've managed to view issues with account mgmt so it's probably worth highlighting this first

**Comment by jmikrut** [comment]
@paulpopus please create a reproduction of this issue and then if you need, let's pair on it. Should be a quick one to fix

**Comment by paulpopus** [comment]
Hey @remy90 thanks for opening this issue

Just tested on `3.0.0-beta.2` and I've not been able to reproduce this. Do you have more information about your configuration or could you provide this reproduction in a repo?

**Comment by remy90** [comment]
I think this can be closed. I think its something to do with dodgy data/my local setup. Cleaning everything down appears to get it working as expected

**Comment by paulpopus** [comment]
Opening because I can reproduce this, it's a problem in a very specific scenario!

**Comment by remy90** [comment]
Ah, sorry about that.. I thought I was going crazy! Doesn't look like I can undelete my comment, apologies! Please do paste it if you received an email with the steps.

**Comment by paulpopus** [comment]
Actually you're double right @remy90 I was getting confused with another thing

What was happening here is that you set `auth: useApiKey: true` on the Posts collection, making that collection the defacto collection for authenticating to the admin panel. This means that when you registered you were registered as a `Post`.
Hence post fields appearing on that form haha

In the future in the payload config admin can take a `user` slug to match the collection you want to authenticate with when dealing with multiple collections that have `auth` configured on them.
